version: '3'

services:
  liver-tumor-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/db
    restart: unless-stopped
    environment:
      - PORT=8000
      - WEBSITES_PORT=8000

volumes:
  db_data: